train:
  batch_size: 65536
  gpus: 0
  lr: 0.0002
  weight_decay: 0.0
  opt_eps: 1.0e-09
  beta1: 0.9
  beta2: 0.999
data:
  image: ./figure/figure2e_nuwave.png
  images:
  - figure\figure2a_orig.png
  - figure\figure2b_linear.png
  - figure\figure2c_u.png
  - figure\figure2d_mu.png
  - figure\figure2e_nuwave.png
arch:
  layers: 8
  channels: 64
  init_scale: 30.0
log:
  name: coin
  checkpoint_dir: checkpoint
  tensorboard_dir: tensorboard
name: coin_10_08_01
